### ISSUE TITLE
'sbt package'  fails due to schema proto files

### ISSUE THREAD

**Issue by nileshkuchekar** [databricks/learning-spark#20]
sbt package

Compiling schema /databricks/learning-spark-master/src/main/protobuf/places.proto
java.lang.RuntimeException: error occured while compiling protobuf files: Cannot run program "protoc": error=2, No such file or directory

Caused by: java.io.IOException: Cannot run program "protoc": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)

Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)

[error](protobuf:protobufGenerate) error occured while compiling protobuf files: Cannot run program "protoc": error=2, No such file or directory

**Comment by nileshkuchekar** [comment]
after some googling: Found that I needed to install 'protobuf', before sbt package

On mac I just did 'brew install protobuf'
and then sbt package worked.
